---
title: "T statistics from resampling"
author: "Mun-Gwan Hong"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: 
      collapse : false
    toc_depth: 3
    code_folding: show
    number_sections: true
    css: styles.css
# bibliography: citations_in_report.bib
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding= encoding, output_dir= "../reports") })
---

```{r, echo=FALSE, include=FALSE, purl=FALSE}
## Set default chunk options
knitr::opts_chunk$set(
  echo = TRUE,
  results = "asis",   # for HTML
  message = FALSE,    # no message from the code
  warning = FALSE,    # no warning from the code
	cache.path = "../cache/",   # cache the results from heavy analyses
	purl = TRUE
)
options(knitr.kable.NA = '')  # NA is shown as ''
```

```{r}
rm(list = ls())

## Pre-loaded packages
# Please note that some functions are called directly from the package using
# double-colon '::' or triple-colon ':::' to make the source clearer.
library(tidyverse)
library(foreach)  # %dopar%, foreach

## File names
fn <- list(
  i = list(                               # input
    olk02 = "../data/s1-olink_proteomic.v02.RData",
    c02 = "../data/s1-clinical.v02.RData"
  ),
  o = list(                               #  output
    perm_t = "../cache/lm_resample_t.RData"
  )
)
# Brief check if all files exist
stopifnot(all(file.exists(unlist(fn$i), dirname(unlist(fn$o)))))

# Load data
load(fn$i$olk02) # proteomic data 
load(fn$i$c02)  # clinical information
# confirm no samples in `qns` without proteomic data
stopifnot(all(qns$SampleID %in% olink$SampleID))

# proteins
proteins <- distinct(olink, OlinkID, Protein = Assay, Panel)

## CONSTANT
N_PERMUTATION = 10000

# Initialize to store T stat from resampling
resample_t_res <- list()
```

```{r}
# stress related variables
stress <- tribble(
  ~lab,                 ~desc,
  "PSQ Total score",    "Stress",
  "HADS_A Total score", "Anxiety",
  "HADS_D Total score", "Depression",
  "HQ Total score",     "Hyperacusis",
  "A15_4",              "Temporomandibular joint pain",
  "A15_1",              "headache"
)
stress_all <- paste0("`", stress$lab, "`", collapse = " + ")
```

### Function for resampling

```{r}
#' Collect T from resampling
#' 
#' This is for adjusting P-value by max-T resampling-based step-down procedure.
#' Because `purrr::nest`is much slower than `pivot_wider`, 'pivot_wider" was 
#' chosen.
#'
#' @param rhs Right hand side of the formula. Left hand side is fixed to "NPX".
#' @param olinkdf a data frame that contain Olink data in long format
#' @param c_data clinical data 
#' @param n_iter number of iterations
#'
#' @return a list of the tibbles of T statistics in each resampling. Each
#'   element of the list is a term in the linear regression model. The first
#'   column of the tibble has the OlinkIDs.
#' @import foreach
#' @importFrom parallel detectCores
#' @importFrom doParallel registerDoParallel
#' @importFrom iterators isample
#' @importFrom digest digest
#'
#' @references 
#' Westfall and Young's max-T method (1993)
#' \url{https://fdhidalgo.github.io/multitestr/articles/multitestr.html#stepdown}

lm_prot_resample_t <- function(rhs, olinkdf, c_data, n_iter = 100) {
  # make sure unique sample IDs in the clinical data table
  stopifnot(anyDuplicated(c_data$SampleID) == 0)
  
  # wide form
  olinkdf_wide <- olinkdf %>% 
    filter(SampleID %in% c_data$SampleID) %>%  # subset analysis
    pivot_wider(SampleID, names_from = OlinkID, values_from = NPX) %>% 
    select(-SampleID)   # no need of SampleID
  # proteins
  prots <- unique(olinkdf$OlinkID)
  
  # trim, because `c_data` can be huge
  c_data <- c_data %>% 
    select(SampleID, all_of(all.vars(formula(paste("~", rhs))))) %>% 
    droplevels()

  # backend for parallel computing
  doParallel::registerDoParallel(cores = parallel::detectCores() - 1)
  
  # T-statistics collected during resampling
  T_rnd <- foreach(
    # resampling
    rnd = iterators::isample(1:nrow(c_data), count = n_iter),
    .inorder = FALSE,
    # .combine = 'cbind',
    .packages = c("dplyr", "purrr")
  ) %dopar% {
    # Olink + randomized clinical data
    oc <- bind_cols(c_data[rnd, ], olinkdf_wide)
    
    # T-statistics from linear regression
    map_dfr(
      prots,
      function(ii) {
        f <- formula(paste(ii, "~", rhs))
        
        # decompose `lm` to speed up
        mf <- model.frame(f, oc, na.action = na.omit)
        y <- model.response(mf, "numeric")
        x <- model.matrix(f, mf)
        z <- lm.fit(x = x, y = y)
        
        # decompose `summary.lm` to speed up
        p <- z$rank
        r <- z$residuals
        rss <- sum(r^2)
        rdf <- z$df.residual
        resvar <- rss/rdf
        Qr <- qr(x)
        p1 <- 1L:p
        R <- chol2inv(Qr$qr[p1, p1, drop = FALSE])
        se <- sqrt(diag(R) * resvar)
        est <- z$coefficients
        (est/se)[-1] # skip (intercept)
      }
    )
  }
  ndigit <- nchar(format(length(T_rnd)))
  sform <- paste0("r%0", ndigit, "d")
  sprintf(sform, 1:length(T_rnd))
  formatC(1:length(T_rnd), width = 2, flag = "0")
  
  mt <- names(T_rnd[[1]])
  # transform to list of terms
  out <- lapply(seq(mt), function(ii) {
    map(T_rnd, ~ unname(.x[, ii])) %>% 
      bind_cols(.name_repair = "minimal") %>% # avoid new names message
      `colnames<-`(sprintf(sform, 1:length(T_rnd))) %>% 
      mutate(OlinkID = prots, .before = 1)
  }) %>% 
    `names<-`(mt)
  # to make sure the same input
  attr(out, "key") <- list(
    rhs = rhs,
    c_data = digest::digest(c_data)
  )
  out
}
```

### Models to test

```{r}
rhs <- list(
  Tinnitus = c(
    "Tinnitus",
    "Tinnitus + Age + Sex",
    "Tinnitus + Age + Sex + `Sample Lab`",
    "Tinnitus + Age + Sex + Smoking",
    "Tinnitus + Age + Sex + `Sample Lab` + Smoking",
    "Tinnitus + Age + Sex + Smoking + TSCHQ_26",
    "Tinnitus + Age + Sex + `Sample Lab` + Smoking + TSCHQ_26",
    # Adjusted for stress related variables
    paste0("Tinnitus + Age + Sex + Smoking + `Sample Lab` + `", stress$lab, "`"),
    paste("Tinnitus + Age + Sex + Smoking + `Sample Lab` +", stress_all)
  )
) %>% 
  lapply(. %>% `names<-`(., .))   # to keep the names after `map` or `lapply`
```

```{r, purl=FALSE, echo=FALSE, results='markup'}
for(ii in names(rhs)) {
  cat("####", ii, "\n ")
  cat(paste0("NPX ~ ", str_remove_all(rhs[[ii]], "`"), "\n"))
}
```

### Overall samples

```{r LM-resample - Overall, cache=TRUE}
# T from resampling for overall samples
resample_t_res$overall <- map(
  rhs$Tinnitus,
  ~ lm_prot_resample_t(.x, olink, qns, n_iter = N_PERMUTATION)
)
```

### Non hearing-aid users

```{r LM-resample - Non-aid_user, cache=TRUE}
# Non-hearing aid users
qns_non_aids <- filter(qns, non_aids_analysis)

# T from resampling for the association of protein with tinnitus
resample_t_res$non_aid_user <- map(
  list(
    "Tinnitus + Age + Sex + `Sample Lab`",
    "Tinnitus + Age + Sex + `Sample Lab` + Smoking + TSCHQ_26"
  ) %>%
    `names<-`(., .),
  ~ lm_prot_resample_t(.x, olink, qns_non_aids, n_iter = N_PERMUTATION)
)
```

### Females only

```{r LM-resample - Female}
# T from resampling for females
qns_sub <- filter(qns, Sex == "Female")
olink_sub <- filter(olink, SampleID %in% qns_sub$SampleID)
resample_t_res$female <- rhs$Tinnitus %>% 
  str_remove(" \\+ Sex") %>%   # remove " + Sex"
  `names<-`(., .) %>% 
  map(~ lm_prot_resample_t(.x, olink_sub, qns_sub, n_iter = N_PERMUTATION))
```

### Males only

```{r LM-resample - Male}
# T from resampling for males
qns_sub <- filter(qns, Sex == "Male")
olink_sub <- filter(olink, SampleID %in% qns_sub$SampleID)
resample_t_res$male <- rhs$Tinnitus %>% 
  str_remove(" \\+ Sex") %>%   # remove " + Sex"
  `names<-`(., .) %>% 
  map(~ lm_prot_resample_t(.x, olink_sub, qns_sub, n_iter = N_PERMUTATION))
```

### Save all

```{r}
save(resample_t_res, file = fn$o$perm_t)
```
